version: "3"
services:
  clickhouse:
    image: 'clickhouse/clickhouse-server'
    ports:
      - '8123:8123'
      - '9000:9000'
      - '9009:9009'
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  redis:
    image: 'redislabs/redismod'
    ports:
        - '6379:6379'

  app:
    image: 'kitime'
    restart: on-failure
    ports:
        - '23:9666'
        - '9100:9100'
    environment:
        - REDIS_HOST=redis:6379
        - KAFKA_HOST=kafka:9092
        - KAFKA_TOPIC=test-topic
        - CLICK_HOST=clickhouse:9000
