apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouse-cluster
  namespace: infra
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
  configuration:
    # zookeeper:
    #   nodes:
    #     - host: zookeeper-0.zookeepers.zoo3ns
    #       port: 2181
    #     - host: zookeeper-1.zookeepers.zoo3ns
    #       port: 2181
    #     - host: zookeeper-2.zookeepers.zoo3ns
    #       port: 2181
    #   session_timeout_ms: 30000
    #   operation_timeout_ms: 10000
    #   root: /path/to/zookeeper/node
    #   identity: user:password
    clusters:
      - name: main
        layout:
          shardsCount: 1
          replicasCount: 2

  templates:
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 35Gi
      - name: log-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi