all:
  children:
    first_master:
      hosts:
        "178.21.11.164":
    masters:
      hosts:
        "89.108.78.30":
        "89.108.76.97":
    workers:
      hosts:
        "89.108.88.237":
        "194.58.120.232":
