all:
  children:
    first_master:
      hosts:
        "194.58.107.108":
    masters:
      hosts:
        "37.140.195.134":
        "185.46.8.166":
    workers:
      hosts:
        "80.78.247.122":
        "185.20.226.76":