
- hosts: localhost
  tasks:
    # MONITORING

    - name: Create monitoring namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: monitoring

    - name: Add kubernetes-dashboard repo
      kubernetes.core.helm_repository:
        name: kubernetes-dashboard
        repo_url: https://kubernetes.github.io/dashboard/

    - name: Deploy kubernetes dashboard
      kubernetes.core.helm:
        name: kubernetes-dashboard
        namespace: monitoring
        chart_ref: kubernetes-dashboard/kubernetes-dashboard

    - name: Create admin-user
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: admin-user
            namespace: kube-system

    - name: ClusterRoleBinding admin-user 
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: admin-user
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          subjects:
          - kind: ServiceAccount
            name: admin-user
            namespace: kube-system


    # INFRA

    - name: Create infra namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: infra

    - name: Install Strimzi kafka operator
      kubernetes.core.k8s:
        state: present
        src: vendor/kafka_operator.yaml

    - name: Deploy kafka
      kubernetes.core.k8s:
        state: present
        src: kafka_config.yaml

    - name: Install Clickhouse operator
      kubernetes.core.k8s:
        state: present
        # src: https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator/clickhouse-operator-install-bundle.yaml
        src: vendor/clickhouse_operator.yaml

    - name: Deploy Clickhouse
      kubernetes.core.k8s:
        state: present
        src: clickhouse_config.yaml

    - name: Add helm repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: Deploy Redis
      kubernetes.core.helm:
        name: redis
        namespace: infra
        chart_ref: bitnami/redis
        values:
          replica:
            replicaCount: 3

